<a href="https://colab.research.google.com/github/kamrulhasan04947/mlprac/blob/main/insurance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Data sets/insurance.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   expenses  1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [ ]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [ ]:
df.duplicated().sum()

1

In [ ]:
df.drop_duplicates()

age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1337 rows x 7 columns]

In [ ]:
from sklearn.preprocessing import LabelBinarizer, LabelEncoder

In [ ]:
lbin = LabelBinarizer()

In [ ]:
lblenc = LabelEncoder()

In [ ]:
# sex column
df['sex'].unique()

array(['female', 'male'], dtype=object)

In [ ]:
# Binary encoding
df['sex'] = lbin.fit_transform(df['sex'])

In [ ]:
df['sex'].unique()

array([0, 1])

In [ ]:
#smoker
df['smoker'].unique()

array(['yes', 'no'], dtype=object)

In [ ]:
df['smoker'] = lbin.fit_transform(df['smoker'])

In [ ]:
df['smoker'].unique()

array([1, 0])

In [ ]:
#region
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [ ]:
df['region'] = lblenc.fit_transform(df['region'])

In [ ]:
df['region'].unique()

array([3, 2, 1, 0])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   int64  
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   int64  
 5   region    1338 non-null   int64  
 6   expenses  1338 non-null   float64
dtypes: float64(2), int64(5)
memory usage: 73.3 KB


In [ ]:
x = df.drop(['expenses'], axis=1)
y= df['expenses']
y

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...   
1333    10600.55
1334     2205.98
1335     1629.83
1336     2007.95
1337    29141.36
Name: expenses, Length: 1338, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,  y, test_size = 0.33, random_state=42)

In [ ]:
linear_reg = LinearRegression()
linerfit = linear_reg.fit(x_train, y_train)
liner_pr = linerfit.predict(x_test)

In [ ]:
print(liner_pr)

[ 8.79186053e+03  7.03602488e+03  3.70032238e+04  9.43358483e+03
  2.70545789e+04  1.08422988e+04  1.48357906e+01  1.72053608e+04
  8.86891136e+02  1.12464985e+04  2.79010281e+04  9.42754920e+03
  5.14441501e+03  3.85487118e+04  4.05828180e+04  3.72391735e+04
  1.52419630e+04  3.59490915e+04  9.08477277e+03  3.15014342e+04
  3.47412065e+03  1.00477955e+04  2.26008946e+03  7.01702957e+03
  1.11737686e+04  1.29702753e+04  1.44812260e+04  5.93532260e+03
  9.79508091e+03  2.18958651e+03  8.74971070e+03  1.31539807e+04
  4.48933528e+03  3.16122078e+03  4.33052071e+03  1.31721303e+04
  1.65890707e+03  8.62078769e+03  3.32742904e+04  3.27172925e+04
  3.38172815e+03  4.35016404e+03  1.40463135e+04  1.16507099e+04
  8.81748384e+03  1.21204035e+04  5.08536218e+03  2.73486082e+03
  3.55719285e+04  9.18352182e+03  1.59721548e+04  2.32339353e+03
  1.23597984e+04  1.40869096e+03  1.36171585e+04  1.25931123e+04
  4.34718195e+03  3.21745268e+04  1.32726168e+04  1.29136741e+04
  1.41375578e+04  1.04010

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score